spring.application.name=result-resource

server.port = 8083
server.servlet.context-path = /result-resource

spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

resilience4j.circuitbreaker.instances.questionService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.questionService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.questionService.waitDurationInOpenState=5s