@startuml

class Question{
    - id : long
    - question : String
    - answer : String
    - marks : int
}

class Option{
    - id : long
    - option_text : String
}

Option "1..*" --* "1" Question : has

interface JpaRepository{
}

interface QuestionRepository{
}
interface OptionRepository{
}

JpaRepository <|-- QuestionRepository
JpaRepository <|-- OptionRepository

class QuestionService{
    + createQuestion(question : Question) : Question
    + getQuestionById(long id) : Question
    + updateQuestionById(id : long, editedQuestion : Question) : Question
    + deleteQuestionById(id : long) : boolean
    + mapToQuestion(dto : QuestionRequestDto) : Question
    + mapToDto(question : Question) : QuestionResponseDto
    + checkAnswerInTheOptions(question : Question) : boolean
}

class QuestionResponseDto{
    - id : long
    - question : String
    - options : List<String>
    - marks : int
}

class QuestionRequestDto{
    - question : String
    - options : List<String>
    - answer : String
    - marks : int
}

QuestionService --> QuestionRepository : uses
QuestionService ..> Question : uses
QuestionService ..> QuestionRequestDto : uses
QuestionService ..> QuestionResponseDto : uses

class QuestionController{
    + createQuestion(dto : QuestionRequestDto) : ResponseEntity<QuestionResponseDto>
    + getQuestionById(id : long) : ResponseEntity<QuestionResponseDto>
    + updateQuestionById(id : long,dto : QuestionRequestDto) : ResponseEntity<QuestionResponseDto>
    + deleteQuestionById(id : long) : ResponseEntity<HttpStatus>
}

QuestionController --> QuestionService : uses
QuestionController ..> QuestionResponseDto : uses
QuestionController ..> QuestionRequestDto : uses

class User{
    - id : long
    - username : String
    - password : String
    - age : int
}

interface UserRepository{
}

UserRepository --|> JpaRepository

class UserService{
    + createUser(user : User) : User
    + updateUser(id : long, user : User) : User
    + getUserByUsername(username : String) : User
    + getUserById(id : long) : User
    + deleteUserById(id : long) : boolean
    + mapToDto(user : User) : UserResponseDto
    + mapToUser(dto : UserRequestDto) : User
}

UserService ..> User : uses

class UserResponseDto{
    - id : long
    - username : String
    - age : int
}

class UserRequestDto{
    - username : String
    - password : String
    - age : int
}

class UserLoginDto{
    - username : String
    - password : String
}

UserService --> UserRepository : uses
UserService ..> UserResponseDto : uses
UserService ..> UserRequestDto : uses

class UserController{
    + login(user : UserLoginDto) : ResponseEntity<UserResponseDto>
    + register(user : UserRequestDto) : ResponseEntity<UserResponseDto>
}

UserController --> UserService : uses
UserController ..> UserResponseDto : uses
UserController ..> UserRequestDto : uses
UserController ..> UserLoginDto : uses
@enduml